### ISSUE TITLE
Add weapon affixes

### ISSUE THREAD

**Issue by niklasgs** [Vadelius/swlsim#13]
**Destruction** - 0.45 * CP When target below <35% HP
**Havoc** - 7.5% CritPower
**Energy** - When using a POWER Ability there is a 33% chance to consume 1 less energy (regardless of cost e.g. 3 or 5)
**Effiency** - Attacks have a 50% chance to reduce 5% of REMAINING cooldown on elite

Also add options for these in GUI.

**Comment by Vadelius** [comment]
Done, will update GUI.
